import { TrendingRides } from "@/app/interfaces/cards/cards"

export const rideContent: TrendingRides[] = [
  {
    id: "1",
    images: ["/images/ride/pics3.png", "/images/ride/pics3.png"],
    type: "Electric",
    title: "Tesla Model 3",
    completeRide: 7,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  },
  {
    id: "2",
    images: [
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
    ],
    type: "Petrol",
    title: "Royce rolls",
    completeRide: 17,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  },
  {
    id: "3",
    images: [
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
    ],
    type: "Petrol",
    title: "Toyota camry",
    completeRide: 10,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  },
  {
    id: "4",
    images: [
      "/images/ride/pics3.png",
      "/images/ride/pics3.png",
      "/images/ride/pics3.png",
      "/images/ride/pics3.png",
      "/images/ride/pics3.png",
    ],
    type: "Electric",
    title: "Tesla Model 3",
    completeRide: 7,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  },
  {
    id: "5",
    images: [
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
      "/images/ride/pics5.png",
    ],
    type: "Petrol",
    title: "Royce rolls",
    completeRide: 17,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  },
  {
    id: "6",
    images: [
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
      "/images/ride/pics4.png",
    ],
    type: "Petrol",
    title: "Toyota camry",
    completeRide: 10,
    rating: 3.4,
    totalRating: 1,
    location: "Obafemi Awolowo way, Lagos, Nigeria",
    status: "Packed",
    seat: '3 seat',
    model: "2022 model",
    auto: "auto",
    gauge: "40km/hrs",
    productType: 'accommodations'
  }
]