import { TrendingCards } from "@/app/interfaces/cards/cards"

export const cardContent: TrendingCards[] = [
  {
    id: "1",
    images: [
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: false,
    rating: "3.8",
    totalRating: "30",
    title: "ParkHall Apartment",
    price: "18",
    time: "night",
    availableFrom: "May 23",
    availableTo: "June 20",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "2",
    images: [
    "/images/workspace/pics9.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: false,
    rating: "3.8",
    totalRating: "30",
    title: "ParkHall Apartment",
    price: "18",
    time: "night",
    availableFrom: "May 23",
    availableTo: "June 20",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "3",
    images: [
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: false,
    rating: "3.8",
    totalRating: "30",
    title: "ParkHall Apartment",
    price: "18",
    time: "night",
    availableFrom: "May 23",
    availableTo: "June 20",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "4",
    images: [
    "/images/workspace/pics7.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    ],
    favorite: true,
    rating: "3.8",
    totalRating: "2",
    title: "Park Conference room",
    price: "20",
    time: "night",
    availableFrom: "May 23",
    availableTo: "June 20",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "5",
    images: [
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: true,
    rating: "3.4",
    totalRating: "1",
    title: "Ferrari Apartment",
    price: "15",
    time: "night",
    availableFrom: "April 17",
    availableTo: "June 12",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "6",
    images: [
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: true,
    rating: "3.8",
    totalRating: "2",
    title: "Park Conference room",
    price: "20",
    time: "night",
    availableFrom: "May 23",
    availableTo: "June 20",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "7",
    images: [
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics7.png",
    ],
    favorite: false,
    rating: "3.8",
    totalRating: "30",
    title: "ParkHall Apartment",
    price: "18",
    time: "night",
    availableFrom: "April 17",
    availableTo: "June 12",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  },
  {
    id: "8",
    images: [
    "/images/workspace/pics8.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics7.png",
    "/images/workspace/pics9.png",
    "/images/workspace/pics8.png",
    ],
    favorite: true,
    rating: "3.4",
    totalRating: "1",
    title: "Ferrari Apartment",
    price: "15",
    time: "night",
    availableFrom: "April 17",
    availableTo: "June 12",
    location: "Lagos, Nigeria.",
    fullAddress: '20 town crescent',
    productType: 'accommodations'
  }
]