import { TrendingCards } from "@/app/interfaces/cards/cards"

export const cardContent: TrendingCards[] = [
  {
    id: '1',
    images: ['/images/workspace/pics4.png', '/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics7.png', '/images/workspace/pics8.png', '/images/workspace/pics9.png'],
    favorite: false,
    rating: '3.8',
    totalRating: '16',
    title: 'ParkHall Private office',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '2',
    images: ['/images/workspace/pics9.png', '/images/workspace/pics8.png', '/images/workspace/pics7.png', '/images/workspace/pics6.png', '/images/workspace/pics5.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '2',
    title: 'Park Conference room',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '3',
    images: ['/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics9.png', '/images/workspace/pics7.png', '/images/workspace/pics8.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.4',
    totalRating: '1',
    title: 'Oriental Hotel Apartment',
    price: '60',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '4',
    images: ['/images/workspace/pics7.png', '/images/workspace/pics6.png', '/images/workspace/pics9.png', '/images/workspace/pics5.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '2',
    title: 'Park Conference room',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '5',
    images: ['/images/workspace/pics5.png', '/images/workspace/pics9.png', '/images/workspace/pics4.png', '/images/workspace/pics7.png', '/images/workspace/pics6.png'],
    favorite: false,
    rating: '3.8',
    totalRating: '16',
    title: 'ParkHall Private office',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '6',
    images: ['/images/workspace/pics4.png', '/images/workspace/pics8.png', '/images/workspace/pics8.png', '/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.4',
    totalRating: '1',
    title: 'Oriental Hotel Apartment',
    price: '60',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  }
]

export const favorites: TrendingCards[] = [
  {
    id: '1',
    images: ['/images/workspace/pics4.png', '/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics7.png', '/images/workspace/pics8.png', '/images/workspace/pics9.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '16',
    title: 'ParkHall Private office',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '2',
    images: ['/images/workspace/pics9.png', '/images/workspace/pics8.png', '/images/workspace/pics7.png', '/images/workspace/pics6.png', '/images/workspace/pics5.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '2',
    title: 'Park Conference room',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '3',
    images: ['/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics9.png', '/images/workspace/pics7.png', '/images/workspace/pics8.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.4',
    totalRating: '1',
    title: 'Oriental Hotel Apartment',
    price: '60',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '4',
    images: ['/images/workspace/pics7.png', '/images/workspace/pics6.png', '/images/workspace/pics9.png', '/images/workspace/pics5.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '2',
    title: 'Park Conference room',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '5',
    images: ['/images/workspace/pics5.png', '/images/workspace/pics9.png', '/images/workspace/pics4.png', '/images/workspace/pics7.png', '/images/workspace/pics6.png'],
    favorite: true,
    rating: '3.8',
    totalRating: '16',
    title: 'ParkHall Private office',
    price: '18',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  },
  {
    id: '6',
    images: ['/images/workspace/pics4.png', '/images/workspace/pics8.png', '/images/workspace/pics8.png', '/images/workspace/pics5.png', '/images/workspace/pics6.png', '/images/workspace/pics4.png'],
    favorite: true,
    rating: '3.4',
    totalRating: '1',
    title: 'Oriental Hotel Apartment',
    price: '60',
    time: 'day',
    availableFrom: 'May 23',
    availableTo: 'June 20',
    location: 'Lagos, Nigeria.',
    fullAddress: '20 town crescent',
    productType: 'workspace'
  }
]